- Applied changes from external development to keep them as examples and use in workflows.

diff --git a/examples/check_pr_release_notes.yml b/examples/check_pr_release_notes.yml
--- a/examples/check_pr_release_notes.yml
+++ b/examples/check_pr_release_notes.yml
@@ -5,9 +5,14 @@ on:
     types: [opened, synchronize, reopened, edited, labeled, unlabeled]
     branches: [ master ]
 
+env:
+  SKIP_LABEL: 'no RN'
+  RLS_NOTES_TAG_REGEX: 'Release Notes:'
+
 jobs:
   check-release-notes:
     runs-on: {your-runner}
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -24,11 +29,11 @@ jobs:
               pull_number: pr_number
             });
             const labels = pr.data.labels ? pr.data.labels.map(label => label.name) : [];
-            
-            // Check if "skip-release-notes-check" label is present
-            if (labels.includes("skip-release-notes-check")) {
-              console.log("Skipping release notes check because 'skip-release-notes-check' label is present.");
+
+            if (labels.includes("${{ env.SKIP_LABEL }}")) {
+              console.log("Skipping release notes check because '${{ env.SKIP_LABEL }}' label is present.");
               core.setOutput("skip_check", 'true');
+              core.setOutput("pr_body", "");
               return;
             }
 
@@ -43,7 +48,7 @@ jobs:
             core.setOutput("skip_check", 'false');
             return;
 
-      - name: Skip check if 'skip-release-notes-check' label is present
+      - name: Skip check if SKIP_LABEL is present
         if: steps.pr_info.outputs.skip_check == 'true'
         run: echo "Skipping release notes validation."
 
@@ -52,18 +57,18 @@ jobs:
         run: |
           # Extract the body from the previous step
           PR_BODY="${{ steps.pr_info.outputs.pr_body }}"
-          
-          # Check if "Release notes:" exists
-          if ! echo "$PR_BODY" | grep -q 'Release Notes:'; then
-            echo "Error: 'Release Notes:' not found in pull request description."
+
+          # Check if "Release Notes:" exists
+          if ! echo "$PR_BODY" | grep -q '${{ env.RLS_NOTES_TAG_REGEX }}'; then
+            echo "Error: release notes tag not found in pull request description. Has to adhere to format '${{ env.RLS_NOTES_TAG_REGEX }}'."
             exit 1
           fi
-          
-          # Extract text after "Release notes:" line
-          RELEASE_NOTES=$(echo "$PR_BODY" | sed -n '/Release.*Notes/,$p' | tail -n +2)
-          
+
+          # Extract text after "Release Notes:" line
+          TEXT_BELOW_RELEASE_NOTES_TAG=$(echo "$PR_BODY" | sed -n '/${{ env.RLS_NOTES_TAG_REGEX }}/,$p' | tail -n +2)
+
           # Check if there's a bullet list (lines starting with '-', '+' or '*')
-          if ! echo "$RELEASE_NOTES" | grep -qE '^\s*[-+*]\s+.+$'; then
-            echo "Error: No bullet list found under 'Release Notes:'."
+          if ! echo "$TEXT_BELOW_RELEASE_NOTES_TAG" | grep -qE '^\s*[-+*]\s+.+$'; then
+            echo "Error: No bullet list found under release notes tag."
             exit 1
           fi
